drop table if exists to_do_card cascade;
create table to_do_card
(
    created_date_time timestamp(6) not null,
    id                bigint generated by default as identity,
    description       varchar(255),
    title             varchar(255) not null,
    user_name         varchar(255) not null,
    primary key (id)
);
