drop table if exists to_do_card cascade;
drop table if exists comment cascade;
create table to_do_card
(
    id                bigint generated by default as identity,
    title             varchar(255) not null,
    description       varchar(255),
    user_name         varchar(255) not null,
    created_date_time timestamp(6) not null,
    is_complete        boolean default false,
    primary key (id)
);
create table comment
(
    id                bigint generated by default as identity,
    content           varchar(255),
    user_name         varchar(255) not null,
    password          varchar(255) not null,
    created_date_time timestamp(6) not null,
    to_do_card_id     bigint not null,
    primary key (id)
)
