/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("kotlinassignment.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))

    // 리플렉션 의존성
    implementation(kotlin("reflect"))
}

application {
    // Define the main class for the application.
    mainClass.set("kotlinassignment.week2.Week2MainKt")
}
