/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("kotlinassignment.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))

    // 코루틴
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2")
}

application {
    // Define the main class for the application.
    mainClass.set("kotlinassignment.week3.Week3MainKt")
}
