drop table if exists to_do_card cascade;
drop table if exists comment cascade;
drop table if exists member cascade;

create table to_do_card
(
    id                bigint generated by default as identity,
    created_at        timestamp(6) not null,
    last_modified_at  timestamp(6) not null,
    deleted_at        timestamp(6),
    member_id         bigint not null,
    title             varchar(255) not null,
    description       varchar(255),
    is_complete       boolean default false,
    category          varchar(31) default null,
    tag               varchar(31) default null,
    state             varchar(31) default null,
    primary key (id)
);
create table comment
(
    id                bigint generated by default as identity,
    created_at        timestamp(6) not null,
    last_modified_at  timestamp(6) not null,
    deleted_at        timestamp(6),
    content           varchar(255),
    member_id         bigint not null,
    to_do_card_id     bigint not null,
    primary key (id)
);
create table member
(
    id                bigint generated by default as identity,
    created_at        timestamp(6) not null,
    deleted_at        timestamp(6),
    last_modified_at  timestamp(6) not null,
    email             varchar(255) not null,
    password          varchar(255) not null,
    nickname          varchar(255) not null,
    primary key (id)
);
